In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('../vacdata/vacancies_2023-04-19.xlsx')

In [3]:
gr = df[['job', 'salary_from', 'salary_to', 'salary_apr']].groupby('job')

In [4]:
gr.describe().round(0).astype('Int64').to_excel('../vacdata/stat.xlsx')

In [5]:
gr.groups.keys()

dict_keys(['HR директор', 'HR менеджер', 'SMM менеджер', 'SMM специалист', 'Администратор в интернет-магазина', 'Бренд менеджер', 'Бухгалтер кассир', 'Бухгалтер на первичку', 'Бухгалтер-оператор', 'Главный бухгалтер', 'Директор по маркетингу', 'Заведующий хозяйством', 'Инженер по эксплуатации зданий', 'Инспектор кадров', 'Интернет маркетолог', 'Категорийный менеджер', 'Коммерческий директор', 'Маркетолог', 'Менеджер интернет-магазин', 'Менеджер по маркетингу', 'Офис менеджер', 'Программист 1С', 'Рекрутер', 'Руководитель отдела маркетинга', 'Системный администратор', 'Специалист технической поддержки', 'Товаровед', 'Управляющий'])

In [6]:
gr.get_group('HR менеджер').describe().round(0).astype('Int64')

       salary_from  salary_to  salary_apr
count           43         30          48
mean         38977      59167       46394
std          11931      31649       18595
min          25000      30000       27000
25%          31000      40000       35000
50%          35000      55500       44000
75%          40000      63750       50925
max          80000     170000      125000

In [7]:
for group in gr.groups.keys():
    print(group)
    print(gr.get_group(group).describe().round(0), '\n')

HR директор
       salary_from  salary_to  salary_apr
count          3.0        1.0         3.0
mean       70000.0   200000.0     90333.0
std        26458.0        NaN     51965.0
min        50000.0   200000.0     55000.0
25%        55000.0   200000.0     60500.0
50%        60000.0   200000.0     66000.0
75%        80000.0   200000.0    108000.0
max       100000.0   200000.0    150000.0

HR менеджер
       salary_from  salary_to  salary_apr
count         43.0       30.0        48.0
mean       38977.0    59167.0     46394.0
std        11931.0    31649.0     18595.0
min        25000.0    30000.0     27000.0
25%        31000.0    40000.0     35000.0
50%        35000.0    55500.0     44000.0
75%        40000.0    63750.0     50925.0
max        80000.0   170000.0    125000.0

SMM менеджер
       salary_from  salary_to  salary_apr
count          4.0        3.0         5.0
mean       29375.0    53333.0     39550.0
std        12970.0    15275.0     10707.0
min        17500.0    40000.0     22000.0
25%        19375.0    45000.0     37500.0
50%        27500.0    50000.0     43750.0
75%        37500.0    60000.0     45000.0
max        45000.0    70000.0     49500.0

SMM специалист
       salary_from  salary_to  salary_apr
count          1.0        1.0         1.0
mean       28000.0    50000.0     39000.0
std            NaN        NaN         NaN
min        28000.0    50000.0     39000.0
25%        28000.0    50000.0     39000.0
50%        28000.0    50000.0     39000.0
75%        28000.0    50000.0     39000.0
max        28000.0    50000.0     39000.0

Администратор в интернет-магазина
       salary_from  salary_to  salary_apr
count          2.0        0.0         2.0
mean       34483.0        NaN     37931.0
std            0.0        NaN         0.0
min        34483.0        NaN     37931.0
25%        34483.0        NaN     37931.0
50%        34483.0        NaN     37931.0
75%        34483.0        NaN     37931.0
max        34483.0        NaN     37931.0

Бренд менеджер
       salary_from  salary_to  salary_apr
count          2.0        1.0         2.0
mean       55000.0    80000.0     68500.0
std        21213.0        NaN     12021.0
min        40000.0    80000.0     60000.0
25%        47500.0    80000.0     64250.0
50%        55000.0    80000.0     68500.0
75%        62500.0    80000.0     72750.0
max        70000.0    80000.0     77000.0

Бухгалтер кассир
       salary_from  salary_to  salary_apr
count          5.0        4.0         6.0
mean       31580.0    29125.0     32067.0
std         7059.0     4802.0      8059.0
min        22500.0    22500.0     22500.0
25%        30000.0    28125.0     27750.0
50%        30000.0    30000.0     31500.0
75%        33400.0    31000.0     33525.0
max        42000.0    34000.0     46200.0

Бухгалтер на первичку
       salary_from  salary_to  salary_apr
count         20.0       15.0        23.0
mean       29380.0    33640.0     31774.0
std         8258.0     9224.0      8014.0
min        15500.0    20000.0     17750.0
25%        25000.0    28000.0     26750.0
50%        26000.0    30000.0     28500.0
75%        35900.0    36800.0     38500.0
max        44000.0    55000.0     49500.0

Бухгалтер-оператор
       salary_from  salary_to  salary_apr
count          6.0        6.0         7.0
mean       28167.0    33833.0     30457.0
std         3817.0     5492.0      4391.0
min        22000.0    25000.0     24200.0
25%        26250.0    31250.0     27500.0
50%        30000.0    35000.0     31500.0
75%        30000.0    37250.0     33750.0
max        32000.0    40000.0     35000.0

Главный бухгалтер
       salary_from  salary_to  salary_apr
count         19.0       12.0        21.0
mean       56734.0    63162.0     61836.0
std        15495.0    14240.0     15308.0
min        35000.0    40000.0     40000.0
25%        42500.0    56250.0     53000.0
50%        60000.0    67000.0     60000.0
75%        70000.0    70000.0     70000.0
max        80000.0    90000.0     88000.0

Директор по маркетингу
       salary_from  salary_to  salary_apr
count          6.0        1.0         6.0
mean       93333.0   150000.0    100167.0
std        34448.0        NaN     33157.0
min        60000.0   150000.0     66000.0
25%        72500.0   150000.0     79750.0
50%        80000.0   150000.0     88000.0
75%       110000.0   150000.0    121000.0
max       150000.0   150000.0    150000.0

Заведующий хозяйством
       salary_from  salary_to  salary_apr
count          5.0        1.0         5.0
mean       38000.0    50000.0     42000.0
std         7583.0        NaN      8419.0
min        30000.0    50000.0     33000.0
25%        35000.0    50000.0     38500.0
50%        35000.0    50000.0     38500.0
75%        40000.0    50000.0     45000.0
max        50000.0    50000.0     55000.0

Инженер по эксплуатации зданий
       salary_from  salary_to  salary_apr
count          3.0        2.0         3.0
mean       41667.0    44000.0     43500.0
std         7638.0     8485.0      6764.0
min        35000.0    38000.0     36500.0
25%        37500.0    41000.0     40250.0
50%        40000.0    44000.0     44000.0
75%        45000.0    47000.0     47000.0
max        50000.0    50000.0     50000.0

Инспектор кадров
       salary_from  salary_to  salary_apr
count         15.0        9.0        16.0
mean       29496.0    36778.0     32399.0
std         8009.0     8043.0      7694.0
min        16440.0    24000.0     18084.0
25%        24500.0    30000.0     27500.0
50%        30000.0    38000.0     33000.0
75%        35000.0    40000.0     37750.0
max        50000.0    50000.0     50000.0

Интернет маркетолог
       salary_from  salary_to  salary_apr
count          4.0        2.0         4.0
mean       31250.0    42500.0     36750.0
std        14361.0     3536.0     13775.0
min        20000.0    40000.0     22000.0
25%        20000.0    41250.0     29875.0
50%        27500.0    42500.0     35000.0
75%        38750.0    43750.0     41875.0
max        50000.0    45000.0     55000.0

Категорийный менеджер
       salary_from  salary_to  salary_apr
count          5.0        3.0         5.0
mean       53000.0    98333.0     66800.0
std        10954.0    43108.0     24936.0
min        40000.0    60000.0     44000.0
25%        50000.0    75000.0     55000.0
50%        50000.0    90000.0     55000.0
75%        55000.0   117500.0     72500.0
max        70000.0   145000.0    107500.0

Коммерческий директор
       salary_from  salary_to  salary_apr
count          1.0        1.0         1.0
mean      120000.0   150000.0    135000.0
std            NaN        NaN         NaN
min       120000.0   150000.0    135000.0
25%       120000.0   150000.0    135000.0
50%       120000.0   150000.0    135000.0
75%       120000.0   150000.0    135000.0
max       120000.0   150000.0    135000.0

Маркетолог
       salary_from  salary_to  salary_apr
count         14.0        5.0        15.0
mean       52143.0   107000.0     60500.0
std        20728.0    59749.0     30968.0
min        25000.0    50000.0     27500.0
25%        36250.0    70000.0     41250.0
50%        45000.0    85000.0     49500.0
75%        68750.0   130000.0     74250.0
max        85000.0   200000.0    140000.0

Менеджер интернет-магазин
       salary_from  salary_to  salary_apr
count          4.0        4.0         4.0
mean       41250.0    50000.0     45625.0
std         8539.0    13540.0     10483.0
min        30000.0    40000.0     35000.0
25%        37500.0    43750.0     40625.0
50%        42500.0    45000.0     43750.0
75%        46250.0    51250.0     48750.0
max        50000.0    70000.0     60000.0

Менеджер по маркетингу
       salary_from  salary_to  salary_apr
count          5.0        3.0         6.0
mean       50000.0    71667.0     52583.0
std        23452.0    18930.0     21207.0
min        25000.0    50000.0     27500.0
25%        35000.0    65000.0     40125.0
50%        45000.0    80000.0     47250.0
75%        60000.0    82500.0     64875.0
max        85000.0    85000.0     85000.0

Офис менеджер
       salary_from  salary_to  salary_apr
count         20.0       15.0        24.0
mean       26359.0    35400.0     30935.0
std         4065.0     8475.0      5317.0
min        15000.0    23000.0     23000.0
25%        25000.0    30000.0     27375.0
50%        25000.0    35000.0     30000.0
75%        29310.0    40000.0     34738.0
max        35000.0    50000.0     45000.0

Программист 1С
       salary_from  salary_to  salary_apr
count         10.0        7.0        10.0
mean      133250.0   155000.0    147725.0
std        28481.0    38188.0     30074.0
min        80000.0    80000.0     80000.0
25%       120000.0   150000.0    138375.0
50%       138750.0   150000.0    150000.0
75%       150000.0   177500.0    166688.0
max       170000.0   200000.0    187000.0

Рекрутер
       salary_from  salary_to  salary_apr
count         24.0       15.0        28.0
mean       36394.0    49733.0     41854.0
std        11792.0    13052.0     12478.0
min        20000.0    30000.0     27000.0
25%        30000.0    40000.0     32625.0
50%        35000.0    50000.0     41362.0
75%        40000.0    60000.0     46125.0
max        80000.0    70000.0     88000.0

Руководитель отдела маркетинга
       salary_from  salary_to  salary_apr
count          4.0        0.0         4.0
mean       82500.0        NaN     90750.0
std        26300.0        NaN     28930.0
min        60000.0        NaN     66000.0
25%        67500.0        NaN     74250.0
50%        75000.0        NaN     82500.0
75%        90000.0        NaN     99000.0
max       120000.0        NaN    132000.0

Системный администратор
       salary_from  salary_to  salary_apr
count         17.0       11.0        19.0
mean       49629.0    63364.0     55009.0
std        13881.0    25610.0     17396.0
min        30000.0    34000.0     30600.0
25%        40000.0    42500.0     44000.0
50%        50000.0    60000.0     55000.0
75%        60000.0    76500.0     64735.0
max        80000.0   110000.0     95000.0

Специалист технической поддержки
       salary_from  salary_to  salary_apr
count         12.0       11.0        16.0
mean       36542.0    52067.0     41882.0
std        18364.0    20593.0     16829.0
min        20000.0    30000.0     27500.0
25%        25750.0    45000.0     35250.0
50%        31000.0    45000.0     38500.0
75%        40375.0    53500.0     43896.0
max        90000.0   110000.0    100000.0

Товаровед
       salary_from  salary_to  salary_apr
count         25.0        3.0        25.0
mean       35870.0    32767.0     39268.0
std         5147.0     5036.0      5829.0
min        24000.0    27000.0     25500.0
25%        34483.0    31000.0     37931.0
50%        34483.0    35000.0     37931.0
75%        37000.0    35650.0     40700.0
max        50000.0    36300.0     55000.0

Управляющий
       salary_from  salary_to  salary_apr
count        119.0       66.0       125.0
mean       65325.0    89048.0     77640.0
std        44415.0    43423.0     49555.0
min        25000.0    33000.0     27500.0
25%        45000.0    60000.0     55000.0
50%        50000.0    75600.0     62500.0
75%        70000.0   103750.0     85000.0
max       300000.0   250000.0    330000.0